input_mesh_file = "torsion.g"
device = "cpu"
type = "single"
output_mesh_file = "torsion_explicit.e"

[model]
type = "solid_mechanics"

    [model.material.blocks]
    torsion = "neohookean"

    [model.material.neohookean]
    density = 1000.0
    poissons_ratio = 0.25
    elastic_modulus = 1.0e9

[time_integrator]
final_time = 2.0e-6
time_step = 5.0e-7
gamma = 0.5
initial_time = 0.0
type = "central_difference"

[[initial_conditions.velocity]]
node_set = "nsall"
function = "a=8000; -a*y*z"
component = "x"
[[initial_conditions.velocity]]
node_set = "nsall"
function = "a=8000; a*x*z"
component = "y"
[[initial_conditions.velocity]]
node_set = "nsall"
function = "0.0"
component = "z"
