input_mesh_file = "tension-specimen.g"
type = "single"
output_mesh_file = "tension-specimen.e"

[[boundary_conditions.dirichlet]]
node_set = "sym_y"
function = "0.0"
component = "y"
[[boundary_conditions.dirichlet]]
node_set = "sym_x"
function = "0.0"
component = "x"
[[boundary_conditions.dirichlet]]
node_set = "sym_z"
function = "0.0"
component = "z"
[[boundary_conditions.dirichlet]]
node_set = "top_y"
function = "0.005 * 0.5 * (1.0 - cos(pi*t))"
component = "y"

[model]
type = "solid_mechanics"

    [model.material.blocks]
    tension = "neohookean"

    [model.material.neohookean]
    density = 1000.0
    poissons_ratio = 0.25
    elastic_modulus = 1.0e9

[time_integrator]
final_time = 1.0
time_step = 0.01
gamma = 0.5
initial_time = 0.0
type = "newmark"
beta = 0.25

[solver]
type = "newton"

    [solver.linear_solver]
    type = "direct"

    [[solver.termination.fail_when_any]]
    maximum_iterations = 16

    [[solver.termination.converge_when_all]]
    minimum_iterations = 0
    [[solver.termination.converge_when_all]]
        [[solver.termination.converge_when_all.any]]
        absolute_residual = 1.0e-5
        [[solver.termination.converge_when_all.any]]
        relative_residual = 1.0e-7
