input_mesh_file = "cantilever.g"
type = "single"
output_mesh_file = "cantilever.e"

[[boundary_conditions.dirichlet]]
node_set = "nsx-"
function = "0.0"
component = "x"
[[boundary_conditions.dirichlet]]
node_set = "nsx-"
function = "0.0"
component = "y"
[[boundary_conditions.dirichlet]]
node_set = "nsx-"
function = "0.0"
component = "z"

[model]
type = "solid_mechanics"

    [model.material.linear_elastic]
    density = 2768.0
    poissons_ratio = 0.25
    elastic_modulus = 6.895e9

    [model.material.blocks]
    cantilever = "linear_elastic"

[time_integrator]
final_time = 3.0e-6
time_step = 1.0e-6
gamma = 0.5
initial_time = 0.0
type = "newmark"
beta = 0.25

[solver]
type = "newton"

    [solver.linear_solver]
    type = "direct"

    [[solver.termination.fail_when_any]]
    maximum_iterations = 16

    [[solver.termination.converge_when_any]]
    absolute_residual = 2.54e-8
    [[solver.termination.converge_when_any]]
    relative_residual = 1.0e-10

[[initial_conditions.displacement]]
node_set = "nsall"
function = "0.393701 * x * x"
component = "y"
