input_mesh_file = "clamped.g"
type = "single"
output_mesh_file = "clamped.e"

[[boundary_conditions.dirichlet]]
node_set = "nsx-"
function = "0.0"
component = "x"
[[boundary_conditions.dirichlet]]
node_set = "nsx+"
function = "0.0"
component = "x"
[[boundary_conditions.dirichlet]]
node_set = "nsy-"
function = "0.0"
component = "y"
[[boundary_conditions.dirichlet]]
node_set = "nsy+"
function = "0.0"
component = "y"
[[boundary_conditions.dirichlet]]
node_set = "nsz-"
function = "0.0"
component = "z"
[[boundary_conditions.dirichlet]]
node_set = "nsz+"
function = "0.0"
component = "z"

[model]
type = "solid_mechanics"

    [model.material.linear_elastic]
    density = 1000.0
    poissons_ratio = 0.0
    elastic_modulus = 1.0e9

    [model.material.blocks]
    clamped = "linear_elastic"

[time_integrator]
final_time = 1.0e-5
time_step = 1.0e-6
gamma = 0.5
initial_time = 0.0
type = "newmark"
beta = 0.25

[solver]
type = "newton"

    [solver.linear_solver]
    type = "direct"

    [[solver.termination.fail_when_any]]
    maximum_iterations = 4

    [[solver.termination.converge_when_all]]
    minimum_iterations = 0
    [[solver.termination.converge_when_all]]
        [[solver.termination.converge_when_all.any]]
        absolute_residual = 1.0e-6
        [[solver.termination.converge_when_all.any]]
        relative_residual = 1.0e-10

[[initial_conditions.displacement]]
node_set = "nsall"
function = "a=0.01; s=0.02; a*exp(-z*z/s/s/2)"
component = "z"
