input_mesh_file = "cube.g"
output_interval = 0.1
type = "single"
output_mesh_file = "cube.e"

[output]
acceleration = true
deformation_gradient = false
stress = true
velocity = true
internal_variables = false

[model]
type = "solid_mechanics"

    [model.material.blocks]
    cube = "neohookean"

    [model.material.neohookean]
    density = 1000.0
    poissons_ratio = 0.25
    elastic_modulus = 1000.0

[time_integrator]
final_time = 1.0
time_step = 0.01
gamma = 0.5
initial_time = 0.0
type = "central_difference"

[[initial_conditions.velocity]]
node_set = "nsall"
function = "1.0"
component = "z"
