input_mesh_file = "tension-specimen.g"
type = "single"
output_mesh_file = "tension-specimen.e"

[[boundary_conditions.dirichlet]]
node_set = "sym_y"
function = "0.0"
component = "y"
[[boundary_conditions.dirichlet]]
node_set = "sym_x"
function = "0.0"
component = "x"
[[boundary_conditions.dirichlet]]
node_set = "sym_z"
function = "0.0"
component = "z"
[[boundary_conditions.dirichlet]]
node_set = "top_y"
function = "0.005 * t"
component = "y"

[model]
type = "solid_mechanics"

    [model.material.blocks]
    tension = "neohookean"

    [model.material.neohookean]
    density = 2700.0
    poissons_ratio = 0.36
    elastic_modulus = 7.0e10

[time_integrator]
increase_factor = 1.5
final_time = 1.0
minimum_time_step = 0.001
maximum_time_step = 0.05
time_step = 0.01
initial_time = 0.0
decrease_factor = 0.5
type = "quasi_static"

[solver]
type = "newton"

    [solver.linear_solver]
    maximum_iterations = 1000
    type = "cg"
    tolerance = 1.0e-8

        [solver.linear_solver.preconditioner]
        type = "jacobi"

    [[solver.termination.fail_when_any]]
    maximum_iterations = 16

    [[solver.termination.converge_when_all]]
    minimum_iterations = 0
    [[solver.termination.converge_when_all]]
        [[solver.termination.converge_when_all.any]]
        absolute_residual = 1.0e-8
        [[solver.termination.converge_when_all.any]]
        relative_residual = 1.0e-12
