input_mesh_file = "tension-specimen.g"
output_interval = 0.01
type = "single"
output_mesh_file = "tension-specimen-dt001.e"

[[boundary_conditions.dirichlet]]
node_set = "sym_y"
function = "0.0"
component = "y"
[[boundary_conditions.dirichlet]]
node_set = "sym_x"
function = "0.0"
component = "x"
[[boundary_conditions.dirichlet]]
node_set = "sym_z"
function = "0.0"
component = "z"
[[boundary_conditions.dirichlet]]
node_set = "top_y"
function = "0.005 * t"
component = "y"

[output]
stress = true
internal_variables = true

[model]
type = "solid_mechanics"

    [model.material.blocks]
    tension = "j2_plasticity"

    [model.material.j2_plasticity]
    density = 2700.0
    poissons_ratio = 0.36
    hardening_modulus = 7.0e8
    yield_stress = 2.5e8
    elastic_modulus = 7.0e10

[time_integrator]
final_time = 1.0
time_step = 0.01
initial_time = 0.0
type = "quasi_static"

[solver]
use_line_search = true
type = "newton"

    [solver.linear_solver]
    type = "direct"

    [[solver.termination.fail_when_any]]
    maximum_iterations = 16

    [[solver.termination.converge_when_all]]
    minimum_iterations = 0
    [[solver.termination.converge_when_all]]
        [[solver.termination.converge_when_all.any]]
        absolute_residual = 1.0e-8
        [[solver.termination.converge_when_all.any]]
        relative_residual = 1.0e-12
