input_mesh_file = "sphere.g"
device = "cpu"
type = "single"
output_mesh_file = "sphere_lbfgs.e"

[model]
type = "solid_mechanics"

    [model.material.blocks]
    sphere = "neohookean"

    [model.material.neohookean]
    density = 1000.0
    poissons_ratio = 0.33
    elastic_modulus = 10000.0

[time_integrator]
final_time = 0.04
time_step = 0.01
gamma = 0.5
initial_time = 0.0
type = "newmark"
beta = 0.25

[solver]
type = "newton"

    [solver.linear_solver]
    history_size = 10
    type = "lbfgs"

    [[solver.termination.fail_when_any]]
    maximum_iterations = 200

    [[solver.termination.converge_when_any]]
    absolute_residual = 1.0e-6
    [[solver.termination.converge_when_any]]
    relative_residual = 1.0e-10

[[initial_conditions.velocity]]
node_set = "sphere_surf"
function = "a=10.0; -a*y*z"
component = "x"
[[initial_conditions.velocity]]
node_set = "sphere_surf"
function = "a=10.0; a*x*z"
component = "y"
[[initial_conditions.velocity]]
node_set = "sphere_surf"
function = "0.0"
component = "z"
