input_mesh_file = "cube.g"
type = "single"
output_mesh_file = "cube.e"

[[boundary_conditions.neumann]]
side_set = "ssz+"
function = "1.0e+09 * t"
component = "z"

[[boundary_conditions.dirichlet]]
side_set = "ssx-"
function = "0.0"
component = "x"
[[boundary_conditions.dirichlet]]
side_set = "ssy-"
function = "0.0"
component = "y"
[[boundary_conditions.dirichlet]]
side_set = "ssz-"
function = "0.0"
component = "z"

[model]
type = "solid_mechanics"

    [model.material.linear_elastic]
    density = 1000.0
    poissons_ratio = 0.25
    elastic_modulus = 1.0e9

    [model.material.blocks]
    cube = "linear_elastic"

[time_integrator]
final_time = 1.0
time_step = 0.1
initial_time = 0.0
type = "quasi_static"

[solver]
type = "newton"

    [solver.linear_solver]
    type = "direct"

    [[solver.termination.fail_when_any]]
    maximum_iterations = 16

    [[solver.termination.converge_when_any]]
    absolute_residual = 1.0e-8
    [[solver.termination.converge_when_any]]
    relative_residual = 1.0e-14
